/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactor.context.propagation.test;

import io.micrometer.context.ContextRegistry;
import io.micrometer.context.ContextSnapshot;

public class App {

    public static void main(String[] args) { // https://micrometer.io/docs/contextPropagation
    }
}
